//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public Caja()
        {
            this.Cata = new HashSet<Cata>();
        }
    
        public System.Guid Id { get; set; }
        public long NumeroCaja { get; set; }
        public Nullable<System.Guid> OrdenVentaId { get; set; }
        public long LoteCaja { get; set; }
        public int Campaña { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public System.Guid ProductoId { get; set; }
        public decimal Bruto { get; set; }
        public decimal Tara { get; set; }
        public decimal Neto { get; set; }
        public Nullable<System.Guid> CataId { get; set; }
        public bool Warrant { get; set; }
    
        public virtual OrdenVenta OrdenVenta { get; set; }
        public virtual ICollection<Cata> Cata { get; set; }
    }
}
