//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public System.Guid Id { get; set; }
        public long NumeroCaja { get; set; }
        public Nullable<System.Guid> OrdenVentaId { get; set; }
        public long LoteCaja { get; set; }
        public int Campaña { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public System.Guid ProductoId { get; set; }
        public decimal Bruto { get; set; }
        public decimal Tara { get; set; }
        public decimal Neto { get; set; }
        public Nullable<System.Guid> CataId { get; set; }
    
        public virtual Cata Cata { get; set; }
    }
}
