//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoDeOrdenDePago
    {
        public ConceptoDeOrdenDePago()
        {
            this.PagoDetalle = new HashSet<PagoDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrdenPagoId { get; set; }
        public System.Guid PesadaId { get; set; }
        public System.Guid ProductorId { get; set; }
        public decimal Kilos { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Neto { get; set; }
        public decimal RetencionIIBB { get; set; }
        public decimal RetencionEEAOC { get; set; }
        public decimal RetencionSaludPublica { get; set; }
        public decimal RetencionGADM { get; set; }
        public decimal RetencionGanancias { get; set; }
        public decimal RetencionRiego { get; set; }
    
        public virtual OrdenPago OrdenPago { get; set; }
        public virtual Pesada Pesada { get; set; }
        public virtual ICollection<PagoDetalle> PagoDetalle { get; set; }
    }
}
