//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CooperativaProduccionEntities : DbContext
    {
        public CooperativaProduccionEntities()
            : base("name=CooperativaProduccionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Cata> Cata { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<ConceptoDeOrdenDePago> ConceptoDeOrdenDePago { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<Contador> Contador { get; set; }
        public virtual DbSet<Movimiento> Movimiento { get; set; }
        public virtual DbSet<OrdenPago> OrdenPago { get; set; }
        public virtual DbSet<OrdenVenta> OrdenVenta { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<PagoDetalle> PagoDetalle { get; set; }
        public virtual DbSet<ParamPagos> ParamPagos { get; set; }
        public virtual DbSet<Pesada> Pesada { get; set; }
        public virtual DbSet<PesadaDetalle> PesadaDetalle { get; set; }
        public virtual DbSet<Preingreso> Preingreso { get; set; }
        public virtual DbSet<PreingresoDetalle> PreingresoDetalle { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Remito> Remito { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vw_Clase> Vw_Clase { get; set; }
        public virtual DbSet<Vw_Cliente> Vw_Cliente { get; set; }
        public virtual DbSet<Vw_ConceptoDeOrdenDePago> Vw_ConceptoDeOrdenDePago { get; set; }
        public virtual DbSet<Vw_Deposito> Vw_Deposito { get; set; }
        public virtual DbSet<Vw_Movimiento> Vw_Movimiento { get; set; }
        public virtual DbSet<Vw_OrdenPago> Vw_OrdenPago { get; set; }
        public virtual DbSet<Vw_Pesada> Vw_Pesada { get; set; }
        public virtual DbSet<Vw_Preingreso> Vw_Preingreso { get; set; }
        public virtual DbSet<Vw_Producto> Vw_Producto { get; set; }
        public virtual DbSet<Vw_Productor> Vw_Productor { get; set; }
        public virtual DbSet<Vw_Provincia> Vw_Provincia { get; set; }
        public virtual DbSet<Vw_ResumenClasePorFecha> Vw_ResumenClasePorFecha { get; set; }
        public virtual DbSet<Vw_ResumenCompraPorClase> Vw_ResumenCompraPorClase { get; set; }
        public virtual DbSet<Vw_ResumenPesada> Vw_ResumenPesada { get; set; }
        public virtual DbSet<Vw_ResumenPesadaPorClase> Vw_ResumenPesadaPorClase { get; set; }
        public virtual DbSet<Vw_ResumenRomaneoBurley> Vw_ResumenRomaneoBurley { get; set; }
        public virtual DbSet<Vw_ResumenRomaneoPorClase> Vw_ResumenRomaneoPorClase { get; set; }
        public virtual DbSet<Vw_ResumenRomaneoVirginia> Vw_ResumenRomaneoVirginia { get; set; }
        public virtual DbSet<Vw_Romaneo> Vw_Romaneo { get; set; }
        public virtual DbSet<Vw_TipoTabaco> Vw_TipoTabaco { get; set; }
    }
}
