//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FardoEnProduccion
    {
        public System.Guid Id { get; set; }
        public System.Guid PesadaDetalleId { get; set; }
        public double Kilos { get; set; }
        public string Unidad { get; set; }
        public Nullable<System.Guid> ProductoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
    }
}
