//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        public System.Guid Id { get; set; }
        public int PuntoVenta { get; set; }
        public long NumInternoLiquidacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Letra { get; set; }
        public System.Guid ProductorId { get; set; }
        public System.Guid ProductoId { get; set; }
        public string Tabaco { get; set; }
        public decimal ImporteNeto { get; set; }
        public decimal IvaPorcentaje { get; set; }
        public decimal IvaCalculado { get; set; }
        public decimal Total { get; set; }
    }
}
