//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        public System.Guid Id { get; set; }
        public int PuntoVenta { get; set; }
        public long NumInternoLiquidacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Letra { get; set; }
        public System.Guid ProductorId { get; set; }
        public System.Guid ProductoId { get; set; }
        public System.Guid TabacoId { get; set; }
        public decimal ImporteNeto { get; set; }
        public decimal IvaPorcentaje { get; set; }
        public decimal IvaCalculado { get; set; }
        public decimal Total { get; set; }
    }
}
