//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenVenta
    {
        public OrdenVenta()
        {
            this.Caja = new HashSet<Caja>();
            this.Cata = new HashSet<Cata>();
            this.OrdenVentaDetalle = new HashSet<OrdenVentaDetalle>();
            this.Remito = new HashSet<Remito>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public long NumOrden { get; set; }
        public long NumOperacion { get; set; }
        public bool Pendiente { get; set; }
        public System.Guid ClienteId { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Piso { get; set; }
        public string Dpto { get; set; }
        public Nullable<System.Guid> TransporteId { get; set; }
        public string Dominio { get; set; }
        public string DominioAcoplado { get; set; }
        public string ApellidoChofer { get; set; }
        public string NombreChofer { get; set; }
        public string CuitChofer { get; set; }
    
        public virtual ICollection<Caja> Caja { get; set; }
        public virtual ICollection<Cata> Cata { get; set; }
        public virtual ICollection<OrdenVentaDetalle> OrdenVentaDetalle { get; set; }
        public virtual ICollection<Remito> Remito { get; set; }
    }
}
