//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenVenta
    {
        public OrdenVenta()
        {
            this.OrdenVentaDetalle = new HashSet<OrdenVentaDetalle>();
            this.Remito = new HashSet<Remito>();
        }
    
        public System.Guid Id { get; set; }
        public long NumOrden { get; set; }
        public long NumOperacion { get; set; }
        public System.Guid ClienteId { get; set; }
        public System.Guid ProductoId { get; set; }
        public Nullable<long> DesdeCaja { get; set; }
        public Nullable<long> HastaCaja { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<bool> Pendiente { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Piso { get; set; }
        public string Dpto { get; set; }
        public Nullable<System.Guid> TransporteId { get; set; }
        public string Dominio { get; set; }
        public string DominioAcoplado { get; set; }
        public string ApellidoChofer { get; set; }
        public string NombreChofer { get; set; }
        public string CuitChofer { get; set; }
    
        public virtual ICollection<OrdenVentaDetalle> OrdenVentaDetalle { get; set; }
        public virtual ICollection<Remito> Remito { get; set; }
    }
}
