//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenVenta
    {
        public OrdenVenta()
        {
            this.Remito = new HashSet<Remito>();
        }
    
        public System.Guid Id { get; set; }
        public long NumOrden { get; set; }
        public long NumOperacion { get; set; }
        public System.Guid ClienteId { get; set; }
        public System.Guid ProductoId { get; set; }
        public Nullable<long> DesdeCaja { get; set; }
        public Nullable<long> HastaCaja { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<bool> Pendiente { get; set; }
    
        public virtual ICollection<Remito> Remito { get; set; }
    }
}
