//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenPago
    {
        public OrdenPago()
        {
            this.ConceptoDeOrdenDePago = new HashSet<ConceptoDeOrdenDePago>();
            this.Pago = new HashSet<Pago>();
        }
    
        public System.Guid Id { get; set; }
        public long NumOrdenPago { get; set; }
        public long NumIntOrdenPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.Guid PesadaId { get; set; }
        public System.Guid ProductorId { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Ganancias { get; set; }
        public Nullable<decimal> GADM { get; set; }
        public Nullable<decimal> IIBB { get; set; }
        public Nullable<decimal> SaludPublica { get; set; }
        public Nullable<decimal> EEAOC { get; set; }
        public Nullable<decimal> Riego { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public string Detalle { get; set; }
    
        public virtual ICollection<ConceptoDeOrdenDePago> ConceptoDeOrdenDePago { get; set; }
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
