//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoDetalle
    {
        public System.Guid Id { get; set; }
        public System.Guid PagoId { get; set; }
        public System.Guid ConceptoId { get; set; }
        public decimal Importe { get; set; }
    
        public virtual ConceptoDeOrdenDePago ConceptoDeOrdenDePago { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
