//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public Pago()
        {
            this.PagoDetalle = new HashSet<PagoDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrdenPagoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
    
        public virtual OrdenPago OrdenPago { get; set; }
        public virtual ICollection<PagoDetalle> PagoDetalle { get; set; }
    }
}
