//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoDetalle
    {
        public System.Guid Id { get; set; }
        public System.Guid PagoId { get; set; }
        public System.Guid ConceptoId { get; set; }
        public decimal Importe { get; set; }
    
        public virtual ConceptoDeOrdenDePago ConceptoDeOrdenDePago { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
