//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamPagos
    {
        public System.Guid id { get; set; }
        public Nullable<decimal> porciento { get; set; }
        public Nullable<decimal> porkilo { get; set; }
    }
}
