//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PesadaDetalle
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PesadaId { get; set; }
        public Nullable<long> NumFardo { get; set; }
        public Nullable<long> ContadorFardo { get; set; }
        public Nullable<System.Guid> ClaseId { get; set; }
        public Nullable<decimal> ClasePrecio { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<System.Guid> ReclasificacionId { get; set; }
        public Nullable<decimal> ReclasificacionPrecio { get; set; }
    }
}
