//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PesadaDetalle
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PesadaId { get; set; }
        public Nullable<long> NumFardo { get; set; }
        public Nullable<System.Guid> ClaseId { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<decimal> PrecioClase { get; set; }
        public Nullable<long> ContadorFardo { get; set; }
        public Nullable<System.Guid> ReclasificacionId { get; set; }
    }
}
