//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pesada
    {
        public System.Guid Id { get; set; }
        public Nullable<int> NumPesada { get; set; }
        public Nullable<System.Guid> PreingresoId { get; set; }
        public Nullable<System.Guid> ProductorId { get; set; }
        public Nullable<int> TotalFardo { get; set; }
        public Nullable<double> TotalKg { get; set; }
        public Nullable<double> ImporteBruto { get; set; }
        public Nullable<double> PrecioPromedio { get; set; }
    }
}
