//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preingreso
    {
        public Preingreso()
        {
            this.PreingresoDetalle = new HashSet<PreingresoDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public string Transporte { get; set; }
        public string Chofer { get; set; }
        public string Patente { get; set; }
        public string NumRemito { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> NumeroPreingreso { get; set; }
    
        public virtual ICollection<PreingresoDetalle> PreingresoDetalle { get; set; }
    }
}
