//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionBlend
    {
        public ProduccionBlend()
        {
            this.ProduccionCorrida = new HashSet<ProduccionCorrida>();
            this.ProduccionMuestra = new HashSet<ProduccionMuestra>();
        }
    
        public System.Guid Id { get; set; }
        public int OrdenProduccion { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<ProduccionCorrida> ProduccionCorrida { get; set; }
        public virtual ICollection<ProduccionMuestra> ProduccionMuestra { get; set; }
    }
}
