//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionHumedadDetalle
    {
        public System.Guid Id { get; set; }
        public System.Guid HumedadId { get; set; }
        public System.TimeSpan Hora { get; set; }
        public long Caja { get; set; }
        public System.Guid CajaId { get; set; }
        public decimal TemperaturaEmpaque { get; set; }
        public int Capsula { get; set; }
        public System.TimeSpan HoraEntrada { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public decimal Humedad { get; set; }
    
        public virtual ProduccionHumedad ProduccionHumedad { get; set; }
    }
}
