//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productor
    {
        public System.Guid Id { get; set; }
        public string Cuit { get; set; }
        public string Fet { get; set; }
        public string Nombre { get; set; }
        public string Provincia { get; set; }
    }
}
