//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionMuestraDetalle
    {
        public System.Guid Id { get; set; }
        public System.Guid MuestraId { get; set; }
        public string Tamanio { get; set; }
        public int Kilos { get; set; }
        public decimal Porcentaje { get; set; }
    
        public virtual ProduccionMuestra ProduccionMuestra { get; set; }
    }
}
