//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionCorrida
    {
        public ProduccionCorrida()
        {
            this.ProduccionNicotina = new HashSet<ProduccionNicotina>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProductoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public long NumeroCorrida { get; set; }
    
        public virtual ProduccionBlend ProduccionBlend { get; set; }
        public virtual ICollection<ProduccionNicotina> ProduccionNicotina { get; set; }
    }
}
