//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionHumedadDetalle
    {
        public System.Guid Id { get; set; }
        public System.Guid HumedadId { get; set; }
        public System.TimeSpan Hora { get; set; }
        public long Caja { get; set; }
        public System.Guid CajaId { get; set; }
        public decimal TemperaturaEmpaque { get; set; }
        public int Capsula { get; set; }
        public System.TimeSpan HoraEntrada { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public decimal Humedad { get; set; }
    
        public virtual ProduccionHumedad ProduccionHumedad { get; set; }
    }
}
