//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionBlend
    {
        public ProduccionBlend()
        {
            this.ProduccionCorrida = new HashSet<ProduccionCorrida>();
            this.ProduccionHumedad = new HashSet<ProduccionHumedad>();
            this.ProduccionMuestra = new HashSet<ProduccionMuestra>();
            this.ProduccionNicotinaDetalle = new HashSet<ProduccionNicotinaDetalle>();
            this.ProduccionTemperatura = new HashSet<ProduccionTemperatura>();
        }
    
        public System.Guid Id { get; set; }
        public int OrdenProduccion { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<ProduccionCorrida> ProduccionCorrida { get; set; }
        public virtual ICollection<ProduccionHumedad> ProduccionHumedad { get; set; }
        public virtual ICollection<ProduccionMuestra> ProduccionMuestra { get; set; }
        public virtual ICollection<ProduccionNicotinaDetalle> ProduccionNicotinaDetalle { get; set; }
        public virtual ICollection<ProduccionTemperatura> ProduccionTemperatura { get; set; }
    }
}
