//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionTemperatura
    {
        public ProduccionTemperatura()
        {
            this.ProduccionTemperaturaDetalle = new HashSet<ProduccionTemperaturaDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.Guid ProductoId { get; set; }
        public long Corrida { get; set; }
        public System.Guid CorridaId { get; set; }
        public string Minimo { get; set; }
        public string Meta { get; set; }
        public string Maximo { get; set; }
    
        public virtual ProduccionBlend ProduccionBlend { get; set; }
        public virtual ICollection<ProduccionTemperaturaDetalle> ProduccionTemperaturaDetalle { get; set; }
    }
}
