//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionNicotinaDetalle
    {
        public System.Guid Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.Guid ProductoId { get; set; }
        public long Corrida { get; set; }
        public System.Guid CorridaId { get; set; }
        public System.TimeSpan Hora { get; set; }
        public long CajaDesde { get; set; }
        public long CajaHasta { get; set; }
        public decimal PorcentajeHumedad { get; set; }
        public decimal Valor1 { get; set; }
        public decimal Valor2 { get; set; }
        public decimal PorcentajeALC { get; set; }
        public decimal PorcentajeNicotina { get; set; }
    
        public virtual ProduccionBlend ProduccionBlend { get; set; }
    }
}
