//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionTemperatura
    {
        public ProduccionTemperatura()
        {
            this.ProduccionTemperaturaDetalle = new HashSet<ProduccionTemperaturaDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.Guid ProductoId { get; set; }
        public long Corrida { get; set; }
        public System.Guid CorridaId { get; set; }
        public string Minimo { get; set; }
        public string Meta { get; set; }
        public string Maximo { get; set; }
    
        public virtual ProduccionBlend ProduccionBlend { get; set; }
        public virtual ICollection<ProduccionTemperaturaDetalle> ProduccionTemperaturaDetalle { get; set; }
    }
}
