//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionTemperaturaDetalle
    {
        public System.Guid Id { get; set; }
        public System.Guid TemperaturaId { get; set; }
        public System.TimeSpan Hora { get; set; }
        public long Caja { get; set; }
        public System.Guid CajaId { get; set; }
        public decimal TemperaturaEmpaque { get; set; }
        public decimal TemperaturaAmbiente { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ProduccionTemperatura ProduccionTemperatura { get; set; }
    }
}
