//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionMuestra
    {
        public ProduccionMuestra()
        {
            this.ProduccionMuestraDetalle = new HashSet<ProduccionMuestraDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public System.Guid ProductoId { get; set; }
        public long Caja { get; set; }
        public System.Guid CajaId { get; set; }
        public long Corrida { get; set; }
        public System.Guid CorridaId { get; set; }
        public int PesoMuestra { get; set; }
        public decimal TotalSobreUnMedio { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ProduccionBlend ProduccionBlend { get; set; }
        public virtual ICollection<ProduccionMuestraDetalle> ProduccionMuestraDetalle { get; set; }
    }
}
