//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito
    {
        public System.Guid Id { get; set; }
        public Nullable<long> NumRemito { get; set; }
        public Nullable<int> PuntoVenta { get; set; }
        public Nullable<long> NumOperacion { get; set; }
        public Nullable<long> NumOrden { get; set; }
        public Nullable<System.Guid> ClienteId { get; set; }
        public Nullable<System.Guid> ProductoId { get; set; }
        public Nullable<long> DesdeCaja { get; set; }
        public Nullable<long> HastaCaja { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public Nullable<System.DateTime> FechaRemito { get; set; }
        public Nullable<System.Guid> OrdenVentaId { get; set; }
        public string PathOrigin { get; set; }
        public string PathSystem { get; set; }
        public byte[] File { get; set; }
    
        public virtual OrdenVenta OrdenVenta { get; set; }
    }
}
