//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public System.Guid Id { get; set; }
        public System.Guid ProductorId { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaTurno { get; set; }
        public decimal Kilos { get; set; }
    }
}
