//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Clase
    {
        public System.Guid ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.Guid> ID_PRODUCTO { get; set; }
        public string COD_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIOCOMPRA { get; set; }
        public Nullable<bool> Vigente { get; set; }
    }
}
