//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_FardoEnProduccionPorHora
    {
        public System.DateTime Fecha { get; set; }
        public string Nombre { get; set; }
        public string TipoTabaco { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> total { get; set; }
        public double C06 { get; set; }
        public double C07 { get; set; }
        public double C08 { get; set; }
        public double C09 { get; set; }
        public double C10 { get; set; }
        public double C11 { get; set; }
        public double C12 { get; set; }
        public double C13 { get; set; }
        public double C14 { get; set; }
        public double C15 { get; set; }
        public double C16 { get; set; }
        public double C17 { get; set; }
        public double C18 { get; set; }
        public double C19 { get; set; }
        public double C20 { get; set; }
    }
}
