//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_LiquidacionAjuste
    {
        public Nullable<System.Guid> ProductorId { get; set; }
        public string Tabaco { get; set; }
        public string NOMBRE { get; set; }
        public string CUIT { get; set; }
        public string nrofet { get; set; }
        public Nullable<decimal> ImporteBruto { get; set; }
        public string Letra { get; set; }
        public string Provincia { get; set; }
    }
}
