//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Movimiento
    {
        public System.Guid Id { get; set; }
        public Nullable<long> NumFardo { get; set; }
        public string Clase { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<long> NumRomaneo { get; set; }
        public string Productor { get; set; }
        public string Fet { get; set; }
        public string Cuit { get; set; }
        public string Provincia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Unidad { get; set; }
        public Nullable<double> Ingreso { get; set; }
        public Nullable<double> Egreso { get; set; }
    }
}
