//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Productor
    {
        public Nullable<System.Guid> ID { get; set; }
        public string CUIT { get; set; }
        public string nrofet { get; set; }
        public string NOMBRE { get; set; }
        public string Provincia { get; set; }
        public string CODIGO { get; set; }
        public string CALLE { get; set; }
        public string DOMICILIO { get; set; }
        public string DENOMINACION { get; set; }
        public string TELEFONO { get; set; }
        public string MAIL { get; set; }
        public string TP { get; set; }
        public string TipoPago { get; set; }
        public string Ciudad { get; set; }
        public string IVA { get; set; }
    }
}
