//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Pesada
    {
        public System.Guid PesadaId { get; set; }
        public System.Guid PesadaDetalleId { get; set; }
        public Nullable<long> NumFardo { get; set; }
        public Nullable<long> ContadorFardo { get; set; }
        public string Clase { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<long> NumRomaneo { get; set; }
        public string Productor { get; set; }
        public string Fet { get; set; }
        public string Cuit { get; set; }
        public string Provincia { get; set; }
    }
}
