//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_RomaneoOrdenPago
    {
        public System.Guid PesadaId { get; set; }
        public Nullable<System.DateTime> FechaRomaneo { get; set; }
        public Nullable<int> PuntoVentaRomaneo { get; set; }
        public Nullable<long> NumRomaneo { get; set; }
        public string Tabaco { get; set; }
        public Nullable<System.Guid> ProductorId { get; set; }
        public string NOMBRE { get; set; }
        public string CUIT { get; set; }
        public string nrofet { get; set; }
        public string IVA { get; set; }
        public Nullable<decimal> IvaCalculado { get; set; }
        public Nullable<double> TotalKg { get; set; }
        public Nullable<decimal> ImporteBruto { get; set; }
        public Nullable<decimal> ImporteNeto { get; set; }
        public Nullable<double> Importeporpagar { get; set; }
        public Nullable<int> PuntoVentaLiquidacion { get; set; }
        public Nullable<long> NumInternoLiquidacion { get; set; }
        public Nullable<System.DateTime> FechaInternaLiquidacion { get; set; }
        public string Letra { get; set; }
        public string Provincia { get; set; }
        public string NumAfipLiquidacion { get; set; }
        public Nullable<System.DateTime> FechaAfipLiquidacion { get; set; }
        public string Cae { get; set; }
        public Nullable<System.DateTime> FechaVtoCae { get; set; }
        public Nullable<System.Guid> OrdenPagoId { get; set; }
        public Nullable<bool> RomaneoPendiente { get; set; }
        public Nullable<decimal> IIBB { get; set; }
        public Nullable<decimal> EEAOC { get; set; }
        public Nullable<decimal> SP { get; set; }
        public Nullable<decimal> GADM { get; set; }
        public Nullable<decimal> RIEGO { get; set; }
        public Nullable<decimal> GANANCIA { get; set; }
        public double BASEGANANCIA { get; set; }
    }
}
