//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ResumenClasePorMes
    {
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Mes { get; set; }
        public System.Guid TabacoId { get; set; }
        public string Tabaco { get; set; }
        public string Clase { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<decimal> PrecioPorKilo { get; set; }
        public Nullable<double> Importe { get; set; }
    }
}
