//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ResumenRomaneoPorClase
    {
        public System.Guid PesadaId { get; set; }
        public string Clase { get; set; }
        public Nullable<int> Fardos { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<decimal> ClasePrecio { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
