//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ResumenRomaneoPorClase
    {
        public System.Guid PesadaId { get; set; }
        public string Clase { get; set; }
        public Nullable<int> Fardos { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<decimal> PrecioClase { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
