//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Romaneo
    {
        public System.Guid PesadaId { get; set; }
        public Nullable<System.DateTime> FechaRomaneo { get; set; }
        public string NumRomaneo { get; set; }
        public Nullable<System.Guid> ProductorId { get; set; }
        public string NOMBRE { get; set; }
        public string CUIT { get; set; }
        public string nrofet { get; set; }
        public string IVA { get; set; }
        public Nullable<double> Totalkg { get; set; }
        public Nullable<decimal> ImporteBruto { get; set; }
        public Nullable<long> numInternoLiquidacion { get; set; }
        public Nullable<System.DateTime> fechaInternaLiquidacion { get; set; }
        public string Letra { get; set; }
        public string Provincia { get; set; }
        public string numAfipLiquidacion { get; set; }
        public Nullable<System.DateTime> fechaAfipLiquidacion { get; set; }
        public string cae { get; set; }
        public Nullable<System.DateTime> fechaVtoCae { get; set; }
        public Nullable<System.Guid> OrdenPagoId { get; set; }
    }
}
