//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ResumenCompraPorClase
    {
        public Nullable<System.DateTime> FechaRomaneo { get; set; }
        public Nullable<int> orden { get; set; }
        public string provincia { get; set; }
        public System.Guid TabacoId { get; set; }
        public string Tabaco { get; set; }
        public Nullable<int> Fardos { get; set; }
        public string Clase { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<double> Importe { get; set; }
    }
}
