//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Stock
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DepositoId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string SUBRUBRO { get; set; }
        public decimal Ingreso { get; set; }
        public decimal Egreso { get; set; }
    }
}
