//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Stock
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DepositoId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string SUBRUBRO { get; set; }
        public decimal Ingreso { get; set; }
        public decimal Egreso { get; set; }
    }
}
