//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Transporte
    {
        public System.Guid ALIAS_0_ID { get; set; }
        public string ALIAS_1_NOMBRE { get; set; }
        public string CUIT { get; set; }
    }
}
